//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinic
    {
        public int ClinicID { get; set; }
        public string ClinicName { get; set; }
        public System.DateTime DateConstruction { get; set; }
        public string ClinicOwner { get; set; }
        public string Adress { get; set; }
        public int FloorNumber { get; set; }
        public int NumberRoomsPerFloor { get; set; }
        public bool Balcony { get; set; }
        public bool Garden { get; set; }
        public int AmbulancesParking { get; set; }
        public int InvalidParking { get; set; }
    }
}
