//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int DoctorID { get; set; }
        public int UniqueNumber { get; set; }
        public int AccountNumber { get; set; }
        public string Department { get; set; }
        public string ShiftWork { get; set; }
        public bool AdmissionOfPatients { get; set; }
        public int ManagerID { get; set; }
        public int UserID { get; set; }
    
        public virtual tblManager tblManager { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
