//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblManager()
        {
            this.tblDoctors = new HashSet<tblDoctor>();
        }
    
        public int ManagerID { get; set; }
        public int FloorNumber { get; set; }
        public string Surname { get; set; }
        public int MaxDoctorNumber { get; set; }
        public int MinRoomsNumber { get; set; }
        public int NumberOfOmissions { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDoctor> tblDoctors { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
